version: "3.5"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    working_dir: /app
    depends_on:
      - redis
    stdin_open: true
    tty: true
  redis:
    image: redis:6
    ports:
      - "6379:6379"